DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     name  VARCHAR(64) NOT NULL,
                                     email VARCHAR(64) UNIQUE NOT NULL,
                                     CONSTRAINT pk_user PRIMARY KEY (id)
);